apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-laravel-app
  labels:
    app: k8s-laravel-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-laravel-app
  template:
    metadata:
      labels:
        app: k8s-laravel-app
    spec:
      containers:
        - name: k8s-laravel-app
          image: k8s-laravel:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
