apiVersion: v1
kind: Service
metadata:
  name: k8s-laravel-app-service
spec:
  selector:
    app: k8s-laravel-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000
